version: 0.1.{build}

cache:
  - node_modules
  - app\node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

platform:
  - x64

init:
  - git config --global core.autocrlf input
  - set PATH=%GOROOT%\bin;%GOPATH%\bin;%PATH%

install:
  - ps: Install-Product node 6 x64
  - git reset --hard HEAD
  - npm install npm -g
  - go version
  - go env
  - go get -u -v github.com/fonero-project/fnod
  - go get -u -v github.com/fonero-project/fnowallet
  - go get -u -v github.com/Masterminds/glide
  - go get -u github.com/golang/dep/cmd/dep
  - cd %GOPATH%\\src\\github.com\\fonero-project\\fnod
  - glide i
  - go install . ./cmd/fnoctl/
  - cd ../fnowallet
  - dep ensure
  - go install
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir bin
  - cp %GOPATH%\\bin\\fnod.exe bin/
  - cp %GOPATH%\\bin\\fnoctl.exe bin/
  - cp %GOPATH%\\bin\\fnowallet.exe bin/
  - npm install

build_script:
  - node --version
  - npm --version
  - npm run package-win

test: off

environment:
  GOPATH: c:\gopath
  GOROOT: C:\go

artifacts:
  - path: 'release\*.exe'
    name: FoneroRelease
